### ISSUE TITLE
Incremental update

### ISSUE THREAD

**Issue by gianarb** [jafarlihi/rssnix#5]
Hello!!

This is a lot of fun thank you for doing that! I would like to know if you are thinking about implementing incremental updates for feeds. According with the logs  during an `update` it looks like all the articles are re-fetched. 

This is an amazing start but if rssnix downloads and notifies only about new articles it never saw before will help me figure out when there is something to read, that I didn't look at yet

have a nice day

**Comment by jafarlihi** [comment]
Sure, sounds good -- will look into implementing it sometime within this week.
Thanks for the suggestion.

**Comment by mattpep** [comment]
I think there are 2 places where the "There are new articles" aspect need to be reported, or at least be visible. The first is during the update phase. But the second is when actually reading; how should a person reading the downloaded content know which of those are the new articles.
One idea which has come to mind is to instead write the article with a prefix of a serial number (leading zeros optional, but IMO it looks neater to have them).

So with a config of

```
[feeds]
example = http://www.example.com/rss.xml
```

articles would be created with the followings names/paths:

```
example/001-An early article
example/002-A subsequent article is this one
example/003-This is the most recently collected article
```

The report at the bottom during the `update` could then read something like

```
INFO[0000] 1 article fetched from feed 'example'  (last seen was 002)        
```

This approach also approaches the second aspect (that of the reader easily finding the new articles) because the user would be able to scroll to the bottom (or top, if using `vim` and have sorted in reverse order) in order to find the new ones. The user would still need to remember which ones they had already read.

Does this seem like a good idea?

**Comment by gianarb** [comment]
I think it is a valid approach but reading your message I thought about another possibility. Let me know what you think about it.

Rssnix can use a hidden file to track stare stare and it can store there the last update. Such value can be used during an update to figure out the new articles since the previous update and those articles can become symbolic links in a new directory called "news" or something like that. In this way the current foldering will stay as it is today. Simple and easy to understand. With this approach during reading the person can check such directory to know what's new.

Just a suggestion coming from the message you have posted 😅

**Comment by mattpep** [comment]
That's definitely a simpler approach. I've modified that proposal ever so slightly by checking existing articles and only writing files if necessary – this way no statefile is needed.

PR is https://github.com/jafarlihi/rssnix/pull/9

**Comment by jafarlihi** [comment]
Done by @mattpep
